name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-latest]
        node: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (macOS)
        if: runner.os == 'macOS'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Node (Windows x64)
        if: runner.os == 'Windows'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: x64

      - name: Install dependencies
        run: npm install

      - name: Build + test
        run: npm test
