name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-artifact-macos:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Upload npm tarball
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: "*.tgz"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.tgz"
          generate_release_notes: true
